### ISSUE TITLE
What about the other auth scheme?

### ISSUE THREAD

**Issue by itewqq** [dogtopus/IllegalSecurityChip#1]
Hello, just discovered your great work here!

But when I researched the nxp A710x series in my ps4 controller, I found that it has another auth mode besides providing a response to the input challenge of 0x100 length. In fact, when I input 0x01 to the chip, it will directly return an ascii code to tell me that it is now in auth2 mode. It seems to provide keep-alive verification for the wireless connection of the handle. Both input and output are 0x20 bytes.

Do you have any research on this verification mechanism? Or there are any guiding directions to study it, such as how you learned about these algorithms. I would be very grateful if you can provide some help!

Finally, thank you again for the great work in this repo.

**Comment by dogtopus** [comment]
Interesting find. I never knew there was an auth2 mode. I reversed the main authentication protocol by sniffing the data and cross-check the result with the data transferred over USB. The authentication protocol over USB and Bluetooth is already documented when I was working on reversing A7105 chips and I found it by searching a bunch of things on Google. I never did any active probing or fuzzing so I'm not aware of anything other than the main mode existed.

So how did you discovered the auth2 mode? Is it used somewhere during controller's normal operation (I assume you have a bluetooth controller since you metioned wireless functionality) or you do some fuzzing to the chip and discovered it?

Also what kind of controller are you using exactly? My protocol documentation was mostly based on protocol captures from my wired Hori Mini controller, probably with some cross-check with my guitar hero dongle which is also USB-only.

**Comment by itewqq** [comment]
Thanks for the quick reply. 

I found it from a schematic diagram from the official document someone gave me. I cannot take a screenshot and share it directly because this document has a digital watermark and is encrypted. However, I manually redrawn the picture, and it shows that there are two parts, auth1 and auth2.

![image](https://user-images.githubusercontent.com/30570177/125028299-5f291980-e0ba-11eb-9d48-e3f939ce22ab.png)

Then I tried to communicate with A7105, and when I input 0x00, it returned a message like this:

```
uart_event_handler()

-------- uart_rxcnt = 1
AUTH1 command!
```

But when I input 0x01 through the serial port, the following message is returned:

```
uart_event_handler()

-------- uart_rxcnt = 1
AUTH2 command!
```

After a lot of searches on the Internet, I saw the repo including yours and the work of passinglink. But no one mentioned auth1 and auth2 here? Or that there are some problems with my understanding...

**Comment by dogtopus** [comment]
Did you send 0x00 and 0x01 to the main microcontroller? A7105 shouldn't output this kind of messages because it uses SCI2C protocol over I2C.

Also from your diagram it looks like `auth1` and `auth2` are just alternative names for `nonce` and `response` in my documentation.

**Comment by dogtopus** [comment]
After some private discussion with OP, looks like this is likely `SET_REPORT` 0x03 and `GET_REPORT` 0x04 which implement a weaker Bluetooth-only (probably symmetrical) auth scheme. This can be added to ISC without hardcoding the secrets used if it's indeed handled by the A7105 chip on Bluetooth-enabled licensed controllers. More details on the exact protocol needed.
